### ISSUE TITLE
MC 1.12.2 ID 1.1.1 Lighting on Facades.

### ISSUE THREAD

**Issue by Splutty** [CyclopsMC/IntegratedDynamics#805] opened 2020-01-24 22:28 UTC
#### Issue type: Lighting on facades is completely wrong and does not take into account either light levels or side of the block.

- :bug: Bug

____

#### Short description:

When making a marble floor and using a facade with a marble block (from "Chisel") the whole Facade block acts as if there's full light shining on it, even when it's in the dark.

#### Steps to reproduce the problem:

See description

#### Expected behaviour:

The 'dark' side of the block to actually be dark.
____

#### Versions:

- This mod:  1.1.1
- Minecraft:  1.12.2
- Forge: 14.23.5.2847
- Chisel: 1.0.1.44

From left to right. Natural Marble Block, XNet Marble Facade block, ID Marble Facade Block.
[https://i.imgur.com/n1mx0uQ.png](url)

**Comment by rubensworks** [comment] 2020-01-25 07:53
Thanks for reporting, but this is a duplicate of #180.

**Closed as completed by rubensworks** 2020-01-25 07:53 UTC
Labels: duplicate
