### ISSUE TITLE
Power API synergy

### ISSUE THREAD

**Issue by TinkerWorX** [CyclopsMC/IntegratedDynamics#52] opened 2016-06-14 22:31 UTC
I've been trying to use IntegratedDynamics with Forestry and Actually Additions, but it seems IntegratedDynamics uses a different RF API. Is there any way to remedy this?

**Comment by rubensworks** [comment] 2016-06-15 06:31
It _should_ be using the same API, I'll look into it.

**Comment by TinkerWorX** [comment] 2016-06-15 07:01
Thank you. For the record I'm using the following versions.
- Actually Additions r44
- Forestry 5.0.13.158
- Integrated Dynamics 0.3.10

**Comment by TinkerWorX** [comment] 2016-06-15 07:08
And here's a picture showing the problem.
![Example](http://i.imgur.com/jKoVPnO.png)

**Comment by rubensworks** [comment] 2016-06-15 07:15
Ah ok, I see the problem. This is not a bug actually, it's just not a feature ;-)
The ID cables only transfer _logic_, not power. You should be able to use machine readers to read RF information about those machines.

It is however perfectly possible to implement power transfer to other mod machines over those cables, I _might_ look into that in the future. But that's not certain yet.

**Comment by TinkerWorX** [comment] 2016-06-15 07:22
Ah, I must've misunderstood because the Energy Battery works with the cables. I appreciate the quick response.

**Comment by Dragnier** [comment] 2016-07-04 16:21
This is a seriously misleading part of the mod... You should change both the cable texture and names to avoid this confusion unless you plan to actually add RF support to the cables. Perhaps make them fiber optic looking and call them logic net cables or something. I downloaded this mod simply because I was trying to find cables for RF without using one of the "big" RF mods like Ender IO and such plus the rest of the mod looked useful. To be honest, I was even disappointed that Charset doesn't have RF wires, only analog redstone ones.

**Comment by rubensworks** [comment] 2016-12-20 18:11
Closing this issue now.
Cables were renamed to "Logic Cables" a while ago,
and with the introduction of [Integrated Tunnels](https://minecraft.curseforge.com/projects/integrated-tunnels/), energy can be transfered to other machines as well.

**Closed as completed by rubensworks** 2016-12-20 18:11 UTC
Labels: mc-1.9, feature
