### ISSUE TITLE
Performance issue for export of list of items

### ISSUE THREAD

**Issue by uhloin** [CyclopsMC/IntegratedDynamics#1344] opened 2024-04-05 12:25 UTC
#### Issue type:

- :bug: Bug 

____

#### Short description:

Exporter of list creates lag for other mods

#### Steps to reproduce the problem:

1. Create a big storage (8x6 double chests with item interfaces and 80K items inside)
2. Create a barrel with exporter and connect network to the barrel
3. Insert a Card with list of items ("Deepslate Nickel Ore", "Deepslate Iron Ore" ) to exporter to row "Export Items"
It's is not important if such ore present in the storage.
After this I can see lags with animation and processing of other mods:
- Xaero Mini Map and Alex's Mobs: Flying Fishes on the minimap move and stop for pause for a second, move and stop
- Xaero Mini Map and Divine RPG: Jungle Bats on the minimap move and pause
- Immersive Engeneering: Wheel of Excavator move and pause
- Thermal Series: Redstone Furnace smelting progress bar move and pause
There are no notable CPU load changes in Task Manager
There are no notable FPS changes in F3 screen
There are no notable lags for player movement animation or particles movement animation 
The computer is powerful enough, normally there are no lags from other mods
4. If insert Card with Item "Deepslate Iron Ore" (not List of Items) there are no lags
5. Even If create 2 exporters and insert 2 Cards with Item "Deepslate Iron Ore" and separate with Item "Deepslate Nickel Ore" there are no lags
6. Also there are no lags if use List but smaller storage (one full double chest)

#### Expected behaviour:

There should not be lags

____

#### Versions:

- This mod: IntegratedDynamics-1.20.1-1.21.2.jar + IntegratedTunnels-1.20.1-1.8.25.jar 
- Minecraft: 1.20.1
- Forge: 47.1.100
Other mods:
Xaeros_Minimap_24.0.3_Forge_1.20.jar 
DivineRPG-1.10.7.3.jar 
ImmersiveEngineering-1.20.1-10.1.0-171.jar 
alexsmobs-1.22.8.jar 
CommonCapabilities-1.20.1-2.9.1.jar

**Comment by rubensworks** [comment] 2024-04-05 12:25
Thanks for reporting!

**Comment by rubensworks** [comment] 2024-04-08 13:26
Could you share a spark log of your game while the lag occurs?
It would also help if you could confirm the lag with the ID network diagnostics (see `/integrateddynamics` command).

**Comment by uhloin** [comment] 2024-04-08 14:26
"see /integrateddynamics" - where is doc for this command?

**Comment by rubensworks** [comment] 2024-04-08 14:31
> Server admins can use the /integrateddynamics networkdiagnostics command to open a gui for detailed ticktime tracking per network part.

https://legacy.curseforge.com/minecraft/mc-mods/integrated-dynamics

<blockquote><img src="https://media.forgecdn.net/avatars/thumbnails/49/396/120/120/636077266568975656.png" width="48" align="right"><div>CurseForge</div><div><strong><a href="https://legacy.curseforge.com/minecraft/mc-mods/integrated-dynamics">Integrated Dynamics</a></strong></div><div>A mod to take full and automated control of your appliances.</div></blockquote>

**Comment by uhloin** [comment] 2024-04-08 14:40
Here is spark results (I was not able upload it, but .zip file below can be unpacked and put to viewer on https://spark.lucko.me/)

![image](https://github.com/CyclopsMC/IntegratedDynamics/assets/96169906/2574b0ac-93b6-49e2-a91f-dbae00efac57)

[sparkprofile.zip](https://github.com/CyclopsMC/IntegratedDynamics/files/14906971/sparkprofile.zip)


<blockquote><img src="https://spark.lucko.me/assets/logo-inverted-512.png" width="48" align="right"><div><strong><a href="https://spark.lucko.me/">spark</a></strong></div><div>spark is a performance profiler for Minecraft clients, servers, and proxies.</div></blockquote>

**Comment by uhloin** [comment] 2024-04-08 14:44
/integrateddynamics networkdiagnostics
![image](https://github.com/CyclopsMC/IntegratedDynamics/assets/96169906/34dba082-bef7-495c-9e00-10c6a4b39dd9)

May be because it was a local game

**Comment by rubensworks** [comment] 2024-04-08 14:47
Thanks @uhloin!
Looks like this is the same as https://github.com/CyclopsMC/IntegratedTunnels/issues/286, so I'm closing this issue here in favor of that one.

> /integrateddynamics networkdiagnostics

Regarding the diagnostics command. Are you an op on your local game? Can you try enabling creative-mode?
If neither of those work, could you open a separate issue for this? Because that command should definitely work.

**Closed as completed by rubensworks** 2024-04-08 14:47 UTC
Labels: bug, performance, more-information-needed, mc-1.20

**Comment by uhloin** [comment] 2024-04-08 15:06
/integrateddynamics networkdiagnostics works in creative mode, but that was single game in survival mode
and there is only "/integrateddynamics version" is possible. Probably because of "no cheats" option.

**Comment by rubensworks** [comment] 2024-04-08 15:38
Ok, then this works as intended, since the diagnostics allow player teleporting. Thanks for checking!

**Comment by uhloin** [comment] 2024-04-08 15:43
And thank you for great mod :)

**Comment by uhloin** [comment] 2024-07-31 11:32
Thank you very much! Looks like my download for 1.20.1 was first :))
