### ISSUE TITLE
Logic cables dont recognize the variable store

### ISSUE THREAD

**Issue by Machine-Maker** [CyclopsMC/IntegratedDynamics#425] opened 2017-11-28 21:13 UTC
#### Issue type:

_Only keep the issue types that are applicable._

- :bug: Bug
____
#### Short description:
I have to replace the variable store every so often

#### Expected behaviour:
I expect that every time I log back on to the server to not have to update the variable store

#### Actual behaviour:
The parts of the ID network show missing variables when the store is clearly attached to the logic cables. Happens (I think) every time the chunks are unloaded for an extended period of time.

#### Steps to reproduce the problem:
Make something, leave the area for a while (on a server) then check if its broken

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: 1.12.2-0.9.6
- CyclopsCore: 1.12.2-0.10.23
- Minecraft: 1.12.2
- Forge: 14.23.1.2556

**Comment by rubensworks** [comment] 2017-12-16 11:23
I'm not able to reproduce this in both single- and multiplayer.
Tried various things with chunk (un)loading, server restarting and placing variable stores in different chunks, and everything keeps working as intended.

I'm going to need more information to reproduce this, such as:
* Can you reproduce this in singleplayer (non-spawn chunks)?
* Can you reproduce this without any other mods installed?
* Does this always happen? Or just sometimes?
* Does it happen for all var stores? Or just some?
* And any other details you can give me.

Related to #239

**Comment by rubensworks** [comment] 2018-01-08 10:13
@X1machinemaker1X Any more information you can give me? Closing this issue otherwise.

**Closed as completed** 2018-01-20 12:29 UTC
Labels: bug, mc-1.12, more-information-needed
