### ISSUE TITLE
Possible Bug With Machine Reader

### ISSUE THREAD

**Issue by squirrelkiller** [CyclopsMC/IntegratedDynamics#41] opened 2016-05-11 02:49 UTC
It does not seem to view a furnace as a machine at all. Is this intended or a bug?

**Comment by rubensworks** [comment] 2016-05-11 06:16
It's not a bug, it's part of an addon mod that isn't released in public just yet.
If you want, you can download test it here: https://dl.bintray.com/cyclopsmc/dev/org/cyclops/commoncapabilities/CommonCapabilities/1.8.9-1.0.0-6/:CommonCapabilities-1.8.9-1.0.0-6.jar
It basically just adds better integration between various machines vanilla and non-vanilla.
But since I plan on doing a lot more with that mod, I haven't released is yet.
Once the EvilCraft update is ready, I'll continue working on that mod :)

**Closed as completed by rubensworks** 2016-05-11 06:16 UTC

**Comment by squirrelkiller** [comment] 2016-05-11 06:40
Purely out of curiosity, why is this being treated as an add-on? It just seems odd that it is not just part of the mod by default, normally that is not the kind of thing I expect to see as an addon, or at least not expect the vanilla portion to be an add on. But just my opinion.

**Comment by rubensworks** [comment] 2016-05-11 06:46
The idea behind CommonCapabilities is that it can be reused across several mods. BuildCraft for example has gates, which also could benefit from this machine information. The way this mod does this is a bit more flexible than how BC currently does this.

It's kinda like why Azanor split up Baubles and Thaumcraft into separate mods.

If it turns out no other mod developers are interested in such a thing, I might merge it into Integrated Dynamics anyways. But I'm not sure about this yet (also part of the reason why I haven't released the mod yet ;) )

**Comment by squirrelkiller** [comment] 2016-05-11 07:00
Makes sense, well my only suggestion is then to do what Baubles and Chicken Lib do when you use TC or CodeChickenCore, and just auto download CommonCapabilities once it is public. Integrated Dynamics is quite powerful (I would know I have been staring at it all day wondering why I decided I wanted to do a tutorial series on something so deep) and I still feel as much as I know about it, which is enough to lead to how many bug reports? I have only scratched the surface, after about 1.5+ hours of video content from the current round of videos I am uploading.

I know I am interested in the idea of CommonCapabilities and if I ever need it for SK Utilities because I need to mod in something myself I will be looking at it.

**Comment by rubensworks** [comment] 2016-05-11 07:05
The bug reports are a good thing :)

I'm not too sure about auto-downloading CommonCapabilities. I'm not very fond of mods installing themselves. Systems like Curse should however handle this pretty well when this mod is used in modpacks.
But I'll have to think about it.
