### ISSUE TITLE
Redstone Writer doesn't causes block update

### ISSUE THREAD

**Issue by Gravlok** [CyclopsMC/IntegratedDynamics#436] opened 2017-12-03 21:39 UTC
- :bug: Bug
____
#### Short description:

Changes of boolean value in Redstone Writer doesn't trigger block update.

#### Expected behaviour:

After inserting empty variable card into Redstone Writer which is connected to path of redstone dust, it should light it up with power of 15.

#### Actual behaviour:

After inserting an empty variable card into Redstone Writer nothing happens with redstone dust unless a manual block update is performed. Same thing occurs when trying to turn it off. Taking out empty card, doesn't make the redstone signal to go down unless a manual block update is performed.

#### Steps to reproduce the problem:

1. Place a piece of redstone dust
2. Place Redstone Writer pointing at redstone dust, add a piece of cable to it
3. Insert empty variable card or boolean true variable into Redstone Writer
4. Place anything near the redstone to force update block
5. To confirm it's not visual bug, place Redstone Reader attached to redstone dust, take it's redstone integer variable, and insert in Display Panel to check power level

#### Additional notes
After further examination of the problem I narrowed down the possible causes. I play on DW20 1.12 modpack which have disabled energy usage by default (in config I:general.energyConsumptionMultiplier=0). In the reproduce steps I purposely skipped "add the battery and connect it to energy source". When the network is powered regardless of the config, the bug above doesn't happen. HOWEVER! If the Redstone Writer is placed BEFORE the network was plugged into power source the bug still happens. What's interesting, inserting an integer card with any value in it works fine, regardless if powered or not.
____
#### Versions:

- This mod: 1.12.2-0.9.6
- CyclopsCore: 1.12.2-0.10.23
- Minecraft: .1.12.2
- Forge: 14.23.1.2555

#### Log file:

N/A

**Comment by rubensworks** [comment] 2017-12-04 01:00
Duplicate of #356.

Thanks for the detailed information though. With this, we finally might be able to reproduce the issue ourselves.

**Closed as completed by rubensworks** 2017-12-04 01:00 UTC
Labels: duplicate
