### ISSUE TITLE
[1.12.2] Crash after disabling Mechanical Drying Basin

### ISSUE THREAD

**Issue by KAfable** [CyclopsMC/IntegratedDynamics#482] opened 2018-01-09 02:37 UTC
#### Issue type: Crash

- :bug: Bug

____
#### Short description:

https://hastebin.com/umilijonan.sql

#### Steps to reproduce the problem:

1. Disable Mechanical Drying Basin in the configs
`    B:mechanical_drying_basin=false
2. Start the game.
____
#### Versions:
- This mod: 0.10.0
- CyclopsCore: 
- Minecraft: 1.12.2
- Forge: 2584

#### Log file:

https://hastebin.com/umilijonan.sql

**Comment by rubensworks** [comment] 2018-01-11 17:25
Can't reproduce this in a clean environment.

Did you by any chance create custom mech drying basin recipes? If so, you have to make sure that `<condition type="config">mechanical_drying_basin</condition>` is present in the recipe, otherwise this crash can occur if the mech drying basin has been disabled, this is intentional.

**Comment by rubensworks** [comment] 2018-01-20 09:38
I just managed to reproduce this in ID Compat, will be fixed in the next version!

**Closed as completed** 2018-01-20 09:40 UTC
Labels: bug, mc-1.12
