### ISSUE TITLE
Annoying Dark shadow!

### ISSUE THREAD

**Issue by LunaSapphie** [CyclopsMC/IntegratedDynamics#1265] opened 2023-04-20 03:13 UTC
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:

1. ...

#### Expected behaviour:

____

#### Versions:

- This mod: IntegratedDynamics (ATM8)
- Minecraft: 1.19.2
- Forge: 1.0.15

**Comment by rubensworks** [comment] 2023-04-20 03:14
Thanks for reporting!

**Comment by rubensworks** [comment] 2023-04-20 06:29
Duplicate of #1254

**Closed as not planned by rubensworks** 2023-04-20 06:29 UTC
Labels: bug, mc-1.19
