### ISSUE TITLE
Facade rendering issue

### ISSUE THREAD

**Issue by Amperthorpe** [CyclopsMC/IntegratedDynamics#35] opened 2016-05-07 08:16 UTC
http://i.imgur.com/nn1rZPs.png
Texture has wrong rotation, and clouds render through it.

**Comment by rubensworks** [comment] 2016-05-07 09:05
How did you achieve this? Is there something special about this (facaded) block? Or are you somehow standing inside that block?

**Comment by Amperthorpe** [comment] 2016-05-07 16:03
Nothing special, just a stone facade. I just right clicked the cables, I'm standing in front of the blocks.

**Comment by rubensworks** [comment] 2016-07-01 21:00
Can't reproduce in latest dev version, assume fixed with the latest rendering changes.

**Closed as completed by rubensworks** 2016-07-01 21:00 UTC
