### ISSUE TITLE
horizon 3 infinite dupplicating when placing 1.12.2-0.10.3

### ISSUE THREAD

**Issue by Gayanfalor** [CyclopsMC/IntegratedDynamics#557] opened 2018-02-25 10:01 UTC
#### Issue type:

- :bug: Bug

#### Short description:
When placing many items like batteries, generator or mechanical squeezer it seems used but if you right click elsewhere it places another one etc infinitelly

#### Expected behaviour:
Working as intended and using correctly the item you placed

#### Steps to reproduce the problem:

1. ...Play horizon 3 v 1.7.0
2. get some menril related items as generator, battery or mech squeezer
3. right click where you want while holding the item

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: 0.10.3
- CyclopsCore: 0.11.1
- Minecraft: 1.12.2
- Forge: 2601

#### Log file:
 there is no crash

**Comment by rubensworks** [comment] 2018-02-25 12:20
You're severely behind on the latest release (0.11.5). Please let me know if you still have this problem with the latest version.

**Comment by Gayanfalor** [comment] 2018-02-25 13:07
Yeah i have seen that when looking on the last update of the pack its 1 month ago 25 janv, maybe the pack is no more updated :'(.

we'll try with my server owner to put updated mod by hand, we have a problem too with the calculator mod wich is fixed in the last ver of calculator mod too so we'll do it by hand same for ID.

Maybe this problem is from spongeforge ?

**Comment by mraof** [comment] 2018-02-28 05:40
I'm getting the same problem with a custom modpack
Minecraft: 1.12.2
Forge: 2611
CyclopsCore: 0.11.4
IntegratedDynamics: 0.11.5
Spongeforge: 2944

**Comment by rubensworks** [comment] 2018-02-28 05:42
@mraof Can you reproduce this _without_ spongeforge? If so, then please report it to the spongeforge issue tracker.

**Comment by rubensworks** [comment] 2018-03-12 06:00
Marking this as a duplicate of #560. Please comment on that issue if there's any more information you can provide.

**Closed as completed by rubensworks** 2018-03-12 06:00 UTC
Labels: more-information-needed
