### ISSUE TITLE
Part Forcefully Unloaded Console Spam

### ISSUE THREAD

**Issue by phit** [CyclopsMC/IntegratedDynamics#283] opened 2017-09-17 20:55 UTC
Mod version: IntegratedDynamics-1.12-0.8.7.jar

```
17.09 16:49:34 [Server] Server thread/WARN [Integrated Dynamics]: Attempted to tick a part that was not properly unloaded. Report this to the Integrated Dynamics issue tracker with details on what you did leading up to this stacktrace. The part was forcefully unloaded 
17.09 16:49:34 [Server] Server thread/INFO [STDERR]: [org.cyclops.integrateddynamics.core.network.Network:update:398]: org.cyclops.integrateddynamics.api.PartStateException: No part state for part at position DimPos(dimensionId=0, blockPos=BlockPos{x=87, y=71, z=-1489}, worldReference=null) side south was found. 
17.09 16:49:34 [Server] INFO World loaded: true 
17.09 16:49:34 [Server] INFO Chunk loaded: false 
17.09 16:49:34 [Server] INFO Part container: null 
17.09 16:49:34 [Server] INFO Parts: null 
17.09 16:49:34 [Server] Server thread/INFO [STDERR]: [org.cyclops.integrateddynamics.core.network.Network:update:398]: at org.cyclops.integrateddynamics.core.network.PartNetworkElement.getPartState(PartNetworkElement.java:96) 
17.09 16:49:34 [Server] Server thread/INFO [STDERR]: [org.cyclops.integrateddynamics.core.network.Network:update:398]: at org.cyclops.integrateddynamics.core.network.PartNetworkElement.getUpdateInterval(PartNetworkElement.java:112) 
17.09 16:49:34 [Server] Server thread/INFO [STDERR]: [org.cyclops.integrateddynamics.core.network.Network:update:398]: at org.cyclops.integrateddynamics.core.network.Network.update(Network.java:375) 
17.09 16:49:34 [Server] Server thread/INFO [STDERR]: [org.cyclops.integrateddynamics.core.network.Network:update:398]: at org.cyclops.integrateddynamics.core.TickHandler.onTick(TickHandler.java:54) 
17.09 16:49:34 [Server] Server thread/INFO [STDERR]: [org.cyclops.integrateddynamics.core.network.Network:update:398]: at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_788_TickHandler_onTick_TickEvent.invoke(.dynamic) 
17.09 16:49:34 [Server] Server thread/INFO [STDERR]: [org.cyclops.integrateddynamics.core.network.Network:update:398]: at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) 
17.09 16:49:34 [Server] Server thread/INFO [STDERR]: [org.cyclops.integrateddynamics.core.network.Network:update:398]: at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:651) 
17.09 16:49:34 [Server] Server thread/INFO [STDERR]: [org.cyclops.integrateddynamics.core.network.Network:update:398]: at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:590) 
17.09 16:49:34 [Server] Server thread/INFO [STDERR]: [org.cyclops.integrateddynamics.core.network.Network:update:398]: at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:264) 
17.09 16:49:34 [Server] Server thread/INFO [STDERR]: [org.cyclops.integrateddynamics.core.network.Network:update:398]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:710) 
17.09 16:49:34 [Server] Server thread/INFO [STDERR]: [org.cyclops.integrateddynamics.core.network.Network:update:398]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) 
17.09 16:49:34 [Server] Server thread/INFO [STDERR]: [org.cyclops.integrateddynamics.core.network.Network:update:398]: at java.lang.Thread.run(Thread.java:748)
```

Using FTB Utilities for chunkloading, player that owns the area logged off and now this is spammed over and over in the console.. loading the area and then leaving does not fix it.

screenshot of the setup in question
![](https://i.imgur.com/Yzxy8V4.png)

**Comment by rubensworks** [comment] 2017-09-18 06:39
Strange, according to my debug code, the chunk must not be loaded (yet), or the tile entity is corrupted.
Can you open the gui of the redstone writer?

**Comment by phit** [comment] 2017-09-18 12:26
![](https://i.imgur.com/cAld9GT.png)

**Comment by rubensworks** [comment] 2017-09-18 12:27
At what frequency does the console logging happen?

Does it still happen when you are opening the part's gui?

Are you sure that _this_ part is causing the problem?

**Comment by phit** [comment] 2017-09-18 12:32
About every 30 seconds or every 600 ticks.

No, it only spams as the debug suggest when the chunk isn't loaded, when I stand next to to it loading the chunk everything is fine.

Yes, I am sure. I have the coordinates in writing in the console logs from the past 24hours or so with these exact coordinates

**Comment by rubensworks** [comment] 2017-09-18 12:36
Ah ok, I misunderstood, I thought the spamming happened even when the chunk was loaded.

In that case, it's possible that the chunk somehow improperly becomes unloaded. The message you see simply makes sure that your ID network doesn't become corrupted when this happens. I assume your ID network still functions as intended after the chunk is reloaded?

Are you experiencing any issues with other tile entities in the same chunk or area? RS or AE systems for example?

**Comment by phit** [comment] 2017-09-18 12:44
Sorry, should have made it more clear. 

No idea what my ID network is, I have never played with your mod. But I haven't heard any complaints about something not working from the player that owns these blocks. Looking at it it seems to do its task.

No, no issues were reported to me.

**Comment by rubensworks** [comment] 2017-09-23 09:43
This may be related to MinecraftForge/MinecraftForge#4413, will put this on hold until that issue is resolved.

**Comment by phit** [comment] 2017-10-15 19:36
still an issue with IntegratedDynamics-1.12-0.9.2 and forge-1.12.2-14.23.0.2512

the issue you linked is fixed as far as I can tell, we havent seen the dataloss in months, either way the tiles in question here never lose data anyway

**Comment by rubensworks** [comment] 2017-10-15 22:27
@phit Forge/Vanilla still has some issues with TileEntities still ticking if their chunk is unloaded, which may be causing this. Until that is resolved, you will see this kind of (harmless) console logging.

At least it's better than the crashing and corruption it used to do ;-)

**Comment by Yorkforce** [comment] 2017-11-05 17:03
Not sure if this is related but we started getting a repeating server crash yesterday with this:
https://pastebin.com/Jh2t9eiT

This was on the Sky Factory 3 modpack with:
IntegratedDynamics v0.7.12
IntegratedTunnels v1.2.5

We had to actually disable the mod just the get the server back up

**Comment by rubensworks** [comment] 2017-11-05 22:31
@Yorkforce I can't see the versions you're using, but you're probably using outdated versions.

**Comment by Yorkforce** [comment] 2017-11-06 10:53
Yeah I figured as much, unfortunately we're stuck with whatever the modpack devs give us but I'll report it to them, thanks anyways.

**Comment by rubensworks** [comment] 2019-01-21 16:59
This issue has been open for a long time now. If this was in fact a Forge issue, it has been fixed (https://github.com/MinecraftForge/MinecraftForge/issues/4413).

Should anyone else be encountering this issue, please let me know here. Closing this issue otherwise.

**Closed as completed** 2019-02-04 17:28 UTC
Labels: bug, mc-1.12, more-information-needed
