### ISSUE TITLE
Smoother editing of aspect's properties

### ISSUE THREAD

**Issue by ZeekDaGeek** [CyclopsMC/IntegratedDynamics#503] opened 2018-01-26 23:16 UTC
#### Issue type:

- :heavy_plus_sign: Feature request

____
#### Short description:
At the moment when you click + to edit properties it's a very clunky system. Lets say you want to edit properties for "Redstone Clock" on a Redstone Reader. Every time you edit one property you have to hit "Write" which takes you back to the list of Aspects.

#### Suggested ways to fix some of the clunkyness:

* When you hit write or "<<" it should save what you've searched so when you go back the search is maintained.
* There are two ways to fix the write button:
  * When you tab through the settings on each property are maintained, at the moment when you switch properties the property you're switching away from will be set back to the saved one. If the write button is going to take you back to the property list then it would be nice if it allowed you to save all of them at once.
  * The write button could be disabled by default until the option has been changed and then when you hit with a valid value it saves and goes back to disabled. Pressing write doesn't bring you back to the aspect list, it just writes the changed property. Pressing "<<" would be the way to get back to the aspect list then.
  * When it comes to the options it comes down to developer preference, I personally like the second option more, but either one would be smoother then the current system when it comes to things like Integrated Tunnels where you're changing a lot more properties, especially with a player simulator. A combination of both could be even better.

____

**Comment by josephcsible** [comment] 2018-01-26 23:17
Duplicate of #379

**Closed as completed by josephcsible** 2018-01-26 23:17 UTC

**Comment by rubensworks** [comment] 2018-01-27 09:43
@ZeekDaGeek Thanks in any case for the suggestions! Added them to the referenced issue.
