### ISSUE TITLE
Add ranged version of Data Readers

### ISSUE THREAD

**Issue by IONayrus** [CyclopsMC/IntegratedDynamics#1245] opened 2023-01-20 21:18 UTC
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

I'm missing an option for especially Block Readers to read a Block at a certain Coordinate. This would be useful if its not possible to reach a face of the Block (for example Draconic Reactor Core which melts every Block around it) or would just allow for much more complex and most of all compact design to be made.

PS, not being able to use all this juicy data makes me wanna cry
![2023-01-20_22 12 38](https://user-images.githubusercontent.com/38812050/213806623-f5889766-96fb-4449-bc44-9520d74a7e1e.png)

**Comment by rubensworks** [comment] 2023-01-20 21:18
Thanks for the suggestion!

**Comment by rubensworks** [comment] 2023-01-21 05:07
Looks like this is a duplicate of #308

**Closed as completed by rubensworks** 2023-01-21 05:07 UTC
Labels: feature-long-term
