### ISSUE TITLE
Redstone Writer doesn't change it's state

### ISSUE THREAD

**Issue by Charismara** [CyclopsMC/IntegratedDynamics#1029] opened 2021-04-23 18:24 UTC
#### Issue type:

- :bug: Bug 

____

#### Short description:

I have created a progamm which reads the cooldown nbt of a botania thermalily and returns true if it's 0.
But the Redstone Writer doesn't change it's state. I need to remove the variable card and add it back again to change the state from false to true and from true to false.

#### Steps to reproduce the problem:

My full programm:

1. Tile Entity NBT (Block Reader)
2. NBT.get_integer with string "cooldown"
3. integer == 0 (this card is in my redstone writer)

#### Expected behaviour:

If the thermaliliy has more than 0 cooldown then it should be false and if the cooldown is 0 it should be true.

____

#### Versions:

- This mod: 1.16.5-1.7.2
- Minecraft: 1.16.5
- Forge: 1.16.5-36.1.6

**Comment by rubensworks** [comment] 2021-04-23 18:24
Thanks for reporting!

**Comment by rubensworks** [comment] 2021-04-23 20:26
Could you check if this also occurs on vanilla blocks? Such as the vanilla chest?

**Comment by Charismara** [comment] 2021-04-24 10:02
> Redstone Writer doesn't change it's state

This also happens if i use a redstone clock variable card instead of the program.

> Could you check if this also occurs on vanilla blocks? Such as the vanilla chest?

Sure, i'm gonna try it now.

:edit
Also happens with vanilla chest.

**Comment by druidbruce** [comment] 2021-04-25 14:45
how far away is the variable store that you put the programmed cards to the redstone writer?
from my experience, a card inside a part which is referencing other cards from a far away variable store won't update regularly unless as you said
> remove the variable card and add it back again to change the state

**Comment by rubensworks** [comment] 2021-04-25 14:46
Are you by any chance using the Performant mod? If so, stop using it, it horribly breaks mods.

**Comment by druidbruce** [comment] 2021-04-25 14:53
> Are you by any chance using the Performant mod? If so, stop using it, it horribly breaks mods.

i wasn't, and i still have to put the cards being referenced to the closest variable store for the cards that are being exposed to update in some circumstances

**Comment by Charismara** [comment] 2021-04-25 15:45
> how far away is the variable store that you put the programmed cards to the redstone writer?

they are in the same chunk.


> Are you by any chance using the Performant mod?

The only performance mod i use is [ferritecore](https://www.curseforge.com/minecraft/mc-mods/ferritecore)

**Comment by rubensworks** [comment] 2021-04-25 15:54
Could you try reproducing this without that mod?

**Comment by Charismara** [comment] 2021-04-25 16:00
> Could you try reproducing this without that mod?

Still happening

**Comment by druidbruce** [comment] 2021-04-25 16:03
> > how far away is the variable store that you put the programmed cards to the redstone writer?
> 
> they are in the same chunk.
> 
> > Are you by any chance using the Performant mod?
> 
> The only performance mod i use is [ferritecore](https://www.curseforge.com/minecraft/mc-mods/ferritecore)

put the variable store right next to the writer, thats what i had to do, my problem was also in the same chunk, and it still didn't update regularly until i put the cards close enough

**Comment by Charismara** [comment] 2021-04-25 18:24
> put the variable store right next to the writer

It seems to work now. Thank you :)

**Comment by druidbruce** [comment] 2021-04-25 18:52
> > put the variable store right next to the writer
> 
> It seems to work now. Thank you :)

ya if somehow u must have a card from a far away variable store, proxy it, and then put that proxy output in the near variable store, thats what i do

**Comment by rubensworks** [comment] 2021-04-25 18:56
Definitely sounds like a bug though

**Comment by druidbruce** [comment] 2021-04-25 19:21
> Definitely sounds like a bug though

id assume keeping it as it is will actually reduce performance cost?

**Comment by rubensworks** [comment] 2021-04-26 17:26
I'm unable to reproduce this myself.

Could you share a world with me that (only) contains a reproducible build, without any other mods installed? (So I can load it into my dev environment)

**Comment by druidbruce** [comment] 2021-05-02 07:47
is there a way to simply copy and paste all Integrated Dynamics blocks/settings/cards from one world to another world? including what they are materialized into and which card is linked to which via which operator?

because to replicate what i have done would take quite a while as it involves quite a few operators, and it will be really hard to figure out which part is actually not updating since multiple parts are involved.

Here is a summary of what i have done.
1. Read from two inventory lists `::[Item]`
2. from the two lists, compare them to another list their size and output another `[Item]` lets call `craftList`
3. from the `craftList` i expose only one of the items to a crafting writer, and the exposed item changes with time (controlled by a counter which advances with time)

my current observations:
in 3. when the counter that controlls the cycle of `Item` has its card that returns the index`::Int` (call this card `Index`)too far away from the crafting writer, the numbers will no longer update once the length of `craftList` reaches 0. When `craftList` actually contains `Item`, it no longer cycle through anything, this is fixed by brining `Index` close to a variable store from the writer.

However, another problem appeared in 2. where the comparison of the two lists `craftList` does not update. This problem isn't consistent, sometimes it does update, sometimes it doesn't, so I am unsure how to deal with this.

**Comment by rubensworks** [comment] 2021-05-02 09:29
> is there a way to simply copy and paste all Integrated Dynamics blocks/settings/cards from one world to another world? including what they are materialized into and which card is linked to which via which operator?

No, not at the moment unfortunately.

It's always possible to share a dedicated world zip, if it doesn't contain other mods.

**Comment by druidbruce** [comment] 2021-05-02 16:23
> if it doesn't contain other mods.

well ya if thats the case i would have sent the world already...

**Comment by druidbruce** [comment] 2021-05-04 15:30
some new info, seems like the problem from step2 can be solved by putting both inventory `[Item]` into two display panels near by. (not sure if nearby is even a requirement though)

> is there a way to simply copy and paste all Integrated Dynamics blocks/settings/cards from one world to another world? including what they are materialized into and which card is linked to which via which operator?
> 
> because to replicate what i have done would take quite a while as it involves quite a few operators, and it will be really hard to figure out which part is actually not updating since multiple parts are involved.
> 
> Here is a summary of what i have done.
> 
> 1. Read from two inventory lists `::[Item]`
> 2. from the two lists, compare them to another list their size and output another `[Item]` lets call `craftList`
> 3. from the `craftList` i expose only one of the items to a crafting writer, and the exposed item changes with time (controlled by a counter which advances with time)
> 
> my current observations:
> in 3. when the counter that controlls the cycle of `Item` has its card that returns the index`::Int` (call this card `Index`)too far away from the crafting writer, the numbers will no longer update once the length of `craftList` reaches 0. When `craftList` actually contains `Item`, it no longer cycle through anything, this is fixed by brining `Index` close to a variable store from the writer.
> 
> However, another problem appeared in 2. where the comparison of the two lists `craftList` does not update. This problem isn't consistent, sometimes it does update, sometimes it doesn't, so I am unsure how to deal with this.

**Comment by rubensworks** [comment] 2021-05-10 17:00
Note to self: also seems to occur on a simple display panel reading the age of cocoa bean blocks.

**Closed as completed** 2021-05-10 18:06 UTC
Labels: bug, mc-1.16
