### ISSUE TITLE
Scrolling / layering issues whith MC-forge-1.16.4-35.1.4

### ISSUE THREAD

**Issue by 7eggert** [CyclopsMC/IntegratedDynamics#972] opened 2021-01-17 08:38 UTC
#### Issue type:

- :bug: Bug 

____

#### Short description:

In readers and interface, if the list of possible slots is longer than the available space, the remaining slots are drawn above the inventory and possible below the screen. I have to scale down the minecraft gui to see them.

In the storage terminal, initially no tab or the storage tab is selected, but the items from the crafting tab above the stored items or above the empty interface.

When creating a crafting job, I can't scroll down.

I believe these to be related; thus I make only one bug report for all these now.
____

#### Versions:

IntegratedCrafting-1.16.4-1.0.10.jar
IntegratedDynamics-1.16.4-1.1.22.jar
IntegratedREST-1.16.4-1.1.2.jar
IntegratedTerminals-1.16.4-1.1.0.jar
IntegratedTunnels-1.16.4-1.6.14.jar

MC-forge-1.16.4-35.1.4

AutoDropper-1.16.3-7.0.0.jar
Basic-Nether-Ores-1.16.4.jar
Big-Buckets-1.16.4.jar
BowInfinityFix-1.16.4.jar
Chargers-1.16.4-3.0.2.4.jar
ChickenChunks-1.16.4-2.7.0.85-universal.jar
CodeChickenLib-1.16.4-3.5.0.401-universal.jar
ColossalChests-1.16.4-1.7.12.jar
CommonCapabilities-1.16.4-2.5.5.jar
Corpse-1.16.4.jar
CraftTweaker-1.16.4-7.1.0.79.jar
CraftingCraft-1.16.4.jar
CyclopsCore-1.16.4-1.9.4.jar
Diamond-Glass-1.16.4.jar
DoubleSlabs-1.16-3.4.10.jar
EditSign-Forge-1.16.4-2.2.0.jar
EnderBags-1.16.2-6.2.0.jar
EnderStorage-1.16.4-2.7.0.161-universal.jar
EverlastingAbilities-1.16.4-1.6.3.jar
Flopper-1.16.4-1.0.6.jar
Futurepack-1.16.4-21.0.4.jar
HarvestWithDispenser-B3.0.0.jar
Large-Fluid-Tank-1.16.4.jar
LavaClearView-1.16.2-1.1.0.jar
More-Charcoal-1.16.4.jar
NaturesCompass-1.16.4-1.8.6.jar
Placebo-1.16.3-4.3.3.jar
RepairChests-1.16.4-1.6.jar
ScalableCatsForce-2.13.3-build-6-with-library.jar
SilentGear-1.16.3-2.4.11+200.jar
SilentLib-1.16.3-4.9.1+64.jar
Simple-Magnets-1.16.4.jar
Solar-Generation-1.16.4.jar
StructuredCrafting-1.16.4-0.2.2.jar
SuperMultiDrills-1.16.3-2.2.0+5.jar
VillagersRespawn-1.16.4-1.16.4-1.35.0.3.jar
WAWLA-1.16.4-7.0.2.jar-
WorldEdit-CUI-FE3-1.16.4-3.0.8.jar
XaerosWorldMap_1.11.8_Forge_1.16.5.jar
Xaeros_Minimap_21.1.0_Forge_1.16.5.jar
aawitherskull_1.16.4-1.1.jar
appliedenergistics2-8.1.0.jar
architectury-1.2.70-forge.jar
backpacked-1.7.0-1.16.3.jar
backpacker-1.1.0-1.16.3.jar
branders-spawnermod-1.16.4-1.7.9.jar
cloth-config-forge-4.1.3.jar
cofh_core-1.16.3-1.1.6.jar
collective-1.16.4-1.53.jar
compact-crafting-1.0.0-alpha.2.jar
compactmachines-4.0.0-alpha.6.jar
extendedcreativeinventory_1.16.4-1.0.jar
fixedanvilrepaircost_1.16.4-1.1.jar
ftb-gui-library-1604.1.1.26.jar
infinitetrading_1.16.4-1.2.jar
invtweaks-1.16.4-1.0.1.jar
ironchest-1.16.4-11.2.10.jar
ironshulkerboxes-1.16.4-5.1.11.jar
itemcollectors-1.0.9-mc1.16.4.jar
jei-1.16.4-7.6.1.65.jar
kubejs-1604.3.4.144-forge.jar
kubejs-thermal-1604.1.0.5.jar
light-overlay-5.6.1.jar
mcjtylib-1.16-5.0.15.jar
mobcatcher-3.1.jar
nametagtweaks_1.16.4-1.2.jar
rftoolsbase-1.16-2.0.9.jar
rftoolsbuilder-1.16-3.0.13.jar
rftoolscontrol-1.16-4.0.6.jar
rftoolspower-1.16-3.0.8.jar
rftoolsstorage-1.16-2.0.8.jar
rftoolsutility-1.16-3.0.20.jar
rhino-1.7.13.10.jar
spiders-2.0-1.16.4-1.0.4.jar
tesseract-1.0.17-mc1.16.4.jar
theoneprobe-1.16-3.0.7.jar
thermal_cultivation-1.16.3-1.1.6.jar
thermal_expansion-1.16.3-1.1.6.jar
thermal_foundation-1.16.3-1.1.6.jar
thermal_innovation-1.16.3-1.1.7.jar
thermal_locomotion-1.16.3-1.1.6.jar
trashcans-1.0.6-mc1.16.4.jar
worldedit-forge-mc1.16.3-7.2.1-dist.jar

**Comment by rubensworks** [comment] 2021-01-17 08:39
Thanks for reporting!

**Comment by rubensworks** [comment] 2021-01-17 08:58
Could you retry with the latest mod versions, and without any other mods installed?

**Comment by 7eggert** [comment] 2021-01-17 09:29
I skipped installing the latest mods because I read the changelog. Trying with fewer mods will take some time (binary search …).

**Comment by 7eggert** [comment] 2021-01-17 13:05
Now with plain forge and only integrated mods:

![2021-01-17_14 01 17](https://user-images.githubusercontent.com/924567/104843842-fad88a80-58cc-11eb-9024-fe0a5ddc0e52.png)

**Comment by rubensworks** [comment] 2021-01-18 18:21
I can't reproduce your problems in the latest version.

I see some items I don't recognize in your inventory, so I assume you have a non-default setup that could break things.

Closing this until a reproducible case can be found.

**Closed as completed by rubensworks** 2021-01-18 18:21 UTC
Labels: bug

**Comment by 7eggert** [comment] 2021-01-19 00:44
Coal, lever, leash, leather, coal ore. (Misa's texture pack)

I found the reason: I'm forced to run Java 14 because one of my mods requires a library that was removed from Java 15.  With only your mods, I can run the bundled java version, then it works correctly.
