### ISSUE TITLE
All vanilla tools are broken, cannot mine anything anymore

### ISSUE THREAD

**Issue by Jack-McKalling** [CyclopsMC/IntegratedDynamics#1242] opened 2022-12-16 09:29 UTC
#### Issue type:

- :bug: Bug 

____

#### Short description:

Since the latest version mentioned below, all vanilla tools (and by extension, modded ones too), are not recognised by the game anymore as the tools that they are.

e.g. TOP mentions "no tool" when looking at stone with a pickaxe, with a big ❌ 
All blocks mine very slowly as if using just your fist, and drop nothing if a tool is required.

#### Steps to reproduce the problem:

1. Get a netherite shovel and pickaxe
2. Delete some grass and dirt
3. Try to mine some stone with the pickaxe
   ⛔ No cobblestone drops

#### Expected behaviour:

All tools are supposed to work, and not behave as if they're just a fancy fist ornament

____

#### Versions:

- Core: 1.17.2
- CC: 2.8.3
- Dynamics: 1.14.2
- Minecraft: 1.19.2
- Forge: 43.2.0

No modpack, not even other Integrated mods installed, just the above 3 mods

**Comment by rubensworks** [comment] 2022-12-16 09:29
Thanks for reporting!

**Comment by Jack-McKalling** [comment] 2022-12-16 09:32
Also important to note, that this is true for _new_ worlds as well.

**Comment by rubensworks** [comment] 2022-12-16 10:13
Duplicate of #1241.

This was already fixed 4 days ago, but curseforge still hasn't approved it. Will force a new release...

**Closed as completed by rubensworks** 2022-12-16 10:13 UTC
Labels: bug, mc-1.19
