### ISSUE TITLE
JEI + click disconnect.

### ISSUE THREAD

**Issue by fobok1** [CyclopsMC/IntegratedDynamics#569] opened 2018-04-19 08:57 UTC
#### Issue type:

_Only keep the issue types that are applicable._

- :bug: Bug

____
#### Short description:

Clicking from JEI into (block or portable) logic programmer causes an immediate disconnect from a server.

#### Expected behaviour:

I expected that the object would appear in the programmer's selection box (as it does in single player) so I could set a variable to that item, and remain connected doing so.

#### Actual behaviour:

I am immediately disconnected from the server.

#### Steps to reproduce the problem:

1. Open the logic programmer. 
2. Select item or list (the only ones I tested, there may be others).
3. Click on an item in JEI to bring up the recipe/worldgen data.
4. Click on the little + icon.

At that point, I am disconnected from the server.
____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: 0.11.10
- CyclopsCore: 0.11.5
- Minecraft: 1.12.2
- Forge: 14.23.2.2627
- Just Enough Items: 4.8.5.159 (also happened with 4.8.5.147)

#### Log file:

[Copied straight from the server shell.](https://www.dropbox.com/s/3avlhc9y7zvw29d/server%20log.txt?dl=0)

[Server's latest.log](https://www.dropbox.com/s/4728gsl6cd3l9ro/latest.log?dl=0)

[fml-junk-earlystartup.log](https://www.dropbox.com/s/8obxbobytsdwmj2/fml-junk-earlystartup.log?dl=0)

**Comment by rubensworks** [comment] 2018-04-29 10:12
Does this happen with all items? Or just one specific item?

(It looks like an issue with a large NBT tag)

**Comment by rubensworks** [comment] 2018-04-29 10:12
Also, do you have the client logs?

**Comment by fobok1** [comment] 2018-05-01 17:52
The test for my previous logs was gold ore, I believe, (I was trying to set up ore processing when I initially discovered this), and for the client logs I'll be including here, I did plain smooth stone just as a test. I also tried a few modded items when I submitted my initial report (so, it's possible the original logs I provided are one of those), to see if it was something specific, but I can't remember what ones I tested then.

[This is the latest.log from my client.](https://www.dropbox.com/s/c7sllafc5o429m1/latest.log?dl=0) Right at the bottom of the log, you'll see I gave myself a logic programmer (I admit it, I was too lazy to run across my base for a quick test), the very next thing I did was try it and get disconnected. Then exited the game to grab the log.

**Comment by rubensworks** [comment] 2018-05-02 06:08
I don't see anything special in the client logs.

The only relevant information in the server logs is this:
```
(CPacketTabComplete) was larger than I expected, found 3 bytes extra whilst reading packet 1
```

This packet is just a vanilla packet, so I don't really know what is going on there.

Can you try reproducing this with just ID+JEI installed? As I'm not able to reproduce this myself here.

**Comment by fobok1** [comment] 2018-05-02 06:59
Okay, I just went and tested that. The same thing happens again, even with just those installed.

[Client latest.log](https://www.dropbox.com/s/bnoshlbgg09b9y2/client%20latest.log?dl=0)
[Server latest.log](https://www.dropbox.com/s/u8cpww7u5qc4exk/latest.log?dl=0)
[Server debug.log](https://www.dropbox.com/s/ut88o50uaux8dil/debug.log?dl=0)

In case it's relevant, I'm connecting to the server through localhost.

**Comment by rubensworks** [comment] 2018-05-02 09:01
Ok, thanks for checking! I'll look into it again soon.

**Comment by rubensworks** [comment] 2018-05-17 18:37
Will be fixed in the next CyclopsCore release.

**Closed as completed** 2018-05-17 18:37 UTC
Labels: bug, mc-1.12
