### ISSUE TITLE
Crafting job stops working when its outputs start getting pulled from storage.

### ISSUE THREAD

**Issue by Yuuva124** [CyclopsMC/IntegratedDynamics#1431] opened 2024-12-06 22:03 UTC
#### Issue type:

- :bug: Bug 

____

#### Short description:

![2024-12-06_12 16 34](https://github.com/user-attachments/assets/70570d3f-f6ef-4938-a027-49737e0ad2f0)
As long as the Create Funnel under the barrel isn't doing anything, the Fluid Encapsulator to the left continuously makes Treated Wood Planks. As soon as I tell the Funnel to start dropping the planks, the Encapsulator will finish making the plank it was working on, then stop, and the crafting job will never be considered complete. The network storage still has more than enough ingredients to keep crafting.
![2024-12-06_12 23 25](https://github.com/user-attachments/assets/fb1e8a63-c779-424e-bed9-0cd18f4f1b73)
In this setup, as long as the conveyor belt is constantly pulling Treated Planks out of the network before they can really enter the barrel, the Encapsulator constantly works. If the belt isn't pulling planks at all and they build up in the barrel, the Encapsulator constantly works. If the belt is pulling items, then I stop the belt and the items start building up in the barrel, it keeps working. If I then start up the belt again and begin pulling items out of the barrel, the Encapsulator stops and the crafting job never completes. Same as the smaller setup, there's still plenty of ingredients.

![2024-12-06_14 00 52](https://github.com/user-attachments/assets/f7147981-c9df-4431-8d1c-42de0e531c39)
Tried with only the Integrated mods and Thermal Expansion, creating mossy cobble instead of Treated Wood Planks. Exact same problem. If I turn the lever off and the hopper starts pulling mossy cobble from the barrel, the Encapsulator stops and the crafting terminal shows the crafting job never being completed.

#### Steps to reproduce the problem:

1. Setup a crafting interface and writer with Treated Wood Planks recipe.
2. Give the network wood and creosote and let it start crafting while filling the storage.
3. Start pulling the Treated Planks out of the network storage.

#### Expected behaviour:

Crafting job should keep running while it still has ingredients available.
____

#### Versions:

- This mod: Dynamics: 1.23.0 Crafting: 1.1.8 Terminals: 1.5.0
- Minecraft: 1.19.2
- Mod loader version:  Forge 43.3.9

**Comment by rubensworks** [comment] 2024-12-06 22:04
Thanks for reporting!

**Comment by rubensworks** [comment] 2024-12-07 05:28
If I understand correctly, the general problem is that a specific item A is being crafted, while at the same time being exported somewhere.
But due to A being exported, it can occur that the crafting job of A will never be marked as completed because it already has been exported at that time before it was detected.
If so, then this is the same problem as https://github.com/CyclopsMC/IntegratedCrafting/issues/81

But since https://github.com/CyclopsMC/IntegratedCrafting/issues/81 has been fixed, this is either a regression, or the setup is different.
Are you sure that you are handling everything through a single ID network? Or do you have multiple seperate networks? (e.g. one crafting network, one exporting network)
In the latter, it could indeed be that some items will not get detected, and there's nothing that can be done about that unfortunately.

**Comment by Yuuva124** [comment] 2024-12-07 05:44
It does sound pretty close, other than the steps making it sound like there are two networks being used. The crafting job running fine until the output starts getting moved is exactly the same, though.

If item A is being exported from the first craft, then exporting causes no problems. It's only after it builds up in a storage for a short time.

I initially had it all set up on a single network, running through a single chest for everything, and it was on a single network in my test world. I did try with two separate networks but it had the same issue so I went back to a single network.

**Comment by rubensworks** [comment] 2024-12-07 05:48
Ok, if it's only a single network, then there's a chance that there's a regression of https://github.com/CyclopsMC/IntegratedCrafting/issues/81 indeed.
Could you try reproducing the problem without any other mods installed with a vanilla recipe?

**Comment by Yuuva124** [comment] 2024-12-07 06:49
With only the Integrated mods, there were no problems. I tried iron nuggets to ingots and making cake. No issues for both. I tried smelting something as well, but it kept saying recipe not acceptable when the crafting interface is aimed at any side of a furnace.

I added the Thermal mods back in and tried smelting some ore using Thermal's furnace. It would work for the first 2-10 crafts, then stop crafting. I had a Sequential Fabricator turning iron nuggets in to iron ingots and it worked fine after starting, stopping, and starting exporting.

**Comment by rubensworks** [comment] 2024-12-07 08:10
> I tried smelting something as well, but it kept saying recipe not acceptable

Wait, that's definitely a problem.
Can you double-check and create a separate bug report for this?

> I added the Thermal mods back in and tried smelting some ore using Thermal's furnace. It would work for the first 2-10 crafts, then stop crafting. I had a Sequential Fabricator turning iron nuggets in to iron ingots and it worked fine after starting, stopping, and starting exporting.

If that's the case with the Thermal furnace, then it will most likely also be the case with the vanilla furnace.

**Comment by Jack-McKalling** [comment] 2024-12-07 14:34
Separate bug now tracked in #1432

**Comment by rubensworks** [comment] 2024-12-09 09:33
@Yuuva124 After fixing #1432, I was not able to reproduce the problem in a vanilla setup unfortunately.
But I may be missing something.
Could you try the [new dev build of Common Capabilities](https://www.dropbox.com/scl/fi/fhxkrhbgwbp8i4lpgqp4z/commoncapabilities-1.19.2-2.9.3-173.jar?rlkey=2a6dslg3qxmx8f0teybvera1i&dl=0), and attempt to reproduce the problem in vanilla (something similar like your Thermal setup for instance)?
If you can reproduce it, could you describe step-by-step how I can reproduce it on my machine? (A clean world download is also fine if that is eaier)

**Comment by rubensworks** [comment] 2024-12-09 09:34
@Jack-McKalling Or if you have any ideas in the meantime, feel free to also have a look at it.

**Comment by Jack-McKalling** [comment] 2024-12-09 09:53
The only idea I have, is this. If both parts of the system are done in the same tick (following that above mentioned fix mentions doing stuff in the same tick), then it could be that in one setup two different things get ticked in the correct order and receive the right information. But that in another setup, if that order is different, the wrong thing gets the info first and then causes this bug.

But this is just a logical deduction, I have no other ideas about this issue (since I'm not experienced with the autocrafting process itself)

**Comment by Yuuva124** [comment] 2024-12-10 00:58
![2024-12-09_16 53 48](https://github.com/user-attachments/assets/d3b6b792-d52b-45f0-98d0-17d572548d76)
![2024-12-09_16 54 00](https://github.com/user-attachments/assets/7c9e3418-7083-400a-b0ac-c085d43c44c2)
I have the Iron Ingot recipe set up exactly like how it worked at the end of #1432, crafting interface and writer both show a green check, but now the crafting terminal is saying it's not allowed. I currently have the version of common capabilities you linked.

**Comment by Yuuva124** [comment] 2024-12-10 01:23
It all works properly now. Looks like the version of common capabilities the modpack is using was the problem. If I had made sure every mod was fully up to date, this wouldn't have been a problem in the first place. Apologies.

**Closed as completed** 2024-12-10 01:31 UTC
Labels: bug, mc-1.19

**Comment by rubensworks** [comment] 2024-12-10 05:32
Glad to hear it's working now, thanks for letting us know @Yuuva124! :-)
