### ISSUE TITLE
Write Button occasionally not working

### ISSUE THREAD

**Issue by squirrelkiller** [CyclopsMC/IntegratedDynamics#42] opened 2016-05-11 02:51 UTC
After an extended period of playtime all instances of the write button fail to perform any form function. Reloading Minecraft completely appears to fix this.

**Comment by rubensworks** [comment] 2016-05-11 06:17
Do you see any errors in the console when this happens?

**Comment by squirrelkiller** [comment] 2016-05-11 06:42
I do not see any errors in the console. No.

**Comment by rubensworks** [comment] 2016-07-01 19:28
I'm unable to reproduce this in MC 1.9.4. It's very likely that it may have been related to an MC bug which is fixed by now.

**Closed as completed by rubensworks** 2016-07-01 19:28 UTC
Labels: bug, mc-1.8, mc-1.9, unreproducible
