### ISSUE TITLE
Cable Dupe when breaking a component in the same block as another component w/o wrench

### ISSUE THREAD

**Issue by moosegold** [CyclopsMC/IntegratedDynamics#128] opened 2017-01-31 20:46 UTC
Breaking a component with anything other than a wrench, when attached to a logic cable and in the same block space as another component will return the expected component, as well as a cable, leaving the cable block in place. The broken component still gets removed.

**Comment by rubensworks** [comment] 2017-02-06 19:20
@moosegold I can't reproduce this, please provide more details: what tool, what position you were in when you break the part, what part of the component you are targeting, ...

**Comment by moosegold** [comment] 2017-02-06 21:29
I've tested it using a diamond pickaxe, a plain fist, a tinker's pickaxe, and an actually editions drill. I've tried aiming at multiple parts of the component, and breaking it from multiple angles. Both pieces fly off in different directions. It only occurs in survival mode, and for me,100% of the time. I just created new instance with only this mod in both 1.10.2 and 1.11.2 (as well as its requirements) using the Curse launcher, to make sure mod compatibility wasn't an issue, but it still persists. I am using forge-12.18.3.2221, running Common Capabilities 1.3.1, Cyclops Core v 0.9.1 and Integrated Dynamics v 0.6.8. The only other information I can think to add is I am running Windows 10, and playing single player. Hopefully this helps, but if it doesn't maybe I'm the only one experiencing the bug and its not a problem.
I included this screenshot of the setup I used for most of the testing, although different setups produced the same result.
![2017-02-06_13 24 12](https://cloud.githubusercontent.com/assets/21247159/22667011/ba3ea3c4-ec6f-11e6-9994-72c1608efa69.png)

**Comment by Runesmacher** [comment] 2017-02-06 22:08
Confirmed, breaking the reader in the ewemble of @moosegold while in survival mode with a diamond pickaxe will pop off the reader and put  it in the inventory, and will make a cable jump away, while leaving the cable and the other reader. 
Will look into it now ;)

**Comment by rubensworks** [comment] 2017-02-13 18:41
@Runesmacher Fixed on master, feel free to double-check if I haven't done anything stupid.

**Closed as completed** 2017-02-13 18:40 UTC
Labels: bug

**Comment by Runesmacher** [comment] 2017-02-13 22:05
I have tested and it seems to work correctly, one thing i noticed (maybe intended beheviour)
Place a reader and then break it (not placed on a cable) => Reader comes back into inventory with no NBT data
Place a reader on a cable then break the reader => Reader comes into inventory with NBT data

**Comment by rubensworks** [comment] 2017-02-14 07:24
@Runesmacher Yep, that's intended. Thanks for testing.
