### ISSUE TITLE
Crash when breaking network

### ISSUE THREAD

**Issue by MinoCraft** [CyclopsMC/IntegratedDynamics#113] opened 2017-01-14 22:17 UTC
Hello o/

I'm playing with Integrated dynamics and I've crashing when I breaked the redstone writer. You can see crash report [here](http://pastebin.com/hrNe0Yq0)

Thanks in advance !

**Comment by rubensworks** [comment] 2017-01-16 12:01
I need more information on how to reproduce this.
The situation that caused the crash, can you reproduce that yourself?
If so, please provide me with more details on that.

**Comment by rubensworks** [comment] 2017-01-17 19:58
@MinoCraft Could you please provide more information? Closing this issue otherwise because I can't reproduce it.

**Closed as completed** 2017-01-19 16:57 UTC
