### ISSUE TITLE
Crash when trying to add first fluid to list of fluids.

### ISSUE THREAD

**Issue by maham** [CyclopsMC/IntegratedDynamics#445] opened 2017-12-09 16:10 UTC
#### Issue type:

- :bug: Bug

____
#### Short description:

I'm trying to create a list of fluids using the portable logic programmer. Graceful crash (showing shutting down message) when clicking the plus sign to add the first fluid.

#### Expected behaviour:

That I can add a fluid like with lists of items.

#### Actual behaviour:

Graceful crash.

#### Steps to reproduce the problem:

1. Open portable logic programmer.
2. Select List.
3. Press the plus sign to add a fluid to the list.
4. Crash.

____
#### Versions:

- This mod: 1.12.2-0.9.6
- CyclopsCore: 1.12.2-0.10.23
- Minecraft: 1.12.2
- Forge: 14.23.1.2555

#### Log file:

https://pastebin.com/akxFCGeU

**Comment by rubensworks** [comment] 2017-12-09 16:12
Please check open issues before reporting new ones, duplicate of #404.

**Closed as completed by rubensworks** 2017-12-09 16:12 UTC
Labels: duplicate
