### ISSUE TITLE
Major log spam

### ISSUE THREAD

**Issue by Sir-Will** [CyclopsMC/IntegratedDynamics#704] opened 2019-03-03 11:25 UTC
Log is being spammed with the following error by integrated dynamics which causes insane performance issues and unreadable logs.

The issue started after the area was regenerated.

IntegratedDynamics-1.12.2-1.0.4
```
[11:52:58] [Server thread/WARN]: [Integrated Dynamics]: Attempted to tick a part that was not properly unloaded. Report this to the Integrated Dynamics issue tracker with details on what you did leading up to this stacktrace. The part was forcefully unloaded
[11:52:58] [Server thread/INFO]: [STDERR]: [org.cyclops.integrateddynamics.core.network.Network:update:430]: org.cyclops.integrateddynamics.api.PartStateException: No part state for part at position DimPos(dimensionId=0, blockPos=BlockPos{x=-1320, y=102, z=-1748}, worldReference=null) side down was found.
World loaded: true
Chunk loaded: true
Part container: null
Parts: null
[11:52:58] [Server thread/INFO]: [STDERR]: [org.cyclops.integrateddynamics.core.network.Network:update:430]: 	at org.cyclops.integrateddynamics.core.network.PartNetworkElement.getPartState(PartNetworkElement.java:108)
[11:52:58] [Server thread/INFO]: [STDERR]: [org.cyclops.integrateddynamics.core.network.Network:update:430]: 	at org.cyclops.integrateddynamics.core.network.PartNetworkElement.getUpdateInterval(PartNetworkElement.java:124)
[11:52:58] [Server thread/INFO]: [STDERR]: [org.cyclops.integrateddynamics.core.network.Network:update:430]: 	at org.cyclops.integrateddynamics.core.network.Network.update(Network.java:407)
[11:52:58] [Server thread/INFO]: [STDERR]: [org.cyclops.integrateddynamics.core.network.Network:update:430]: 	at org.cyclops.integrateddynamics.core.TickHandler.onTick(TickHandler.java:65)
[11:52:58] [Server thread/INFO]: [STDERR]: [org.cyclops.integrateddynamics.core.network.Network:update:430]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1181_TickHandler_onTick_TickEvent.invoke(.dynamic)
[11:52:58] [Server thread/INFO]: [STDERR]: [org.cyclops.integrateddynamics.core.network.Network:update:430]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[11:52:58] [Server thread/INFO]: [STDERR]: [org.cyclops.integrateddynamics.core.network.Network:update:430]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:687)
[11:52:58] [Server thread/INFO]: [STDERR]: [org.cyclops.integrateddynamics.core.network.Network:update:430]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:641)
[11:52:58] [Server thread/INFO]: [STDERR]: [org.cyclops.integrateddynamics.core.network.Network:update:430]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
[11:52:58] [Server thread/INFO]: [STDERR]: [org.cyclops.integrateddynamics.core.network.Network:update:430]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712)
[11:52:58] [Server thread/INFO]: [STDERR]: [org.cyclops.integrateddynamics.core.network.Network:update:430]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[11:52:58] [Server thread/INFO]: [STDERR]: [org.cyclops.integrateddynamics.core.network.Network:update:430]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by rubensworks** [comment] 2019-03-03 16:56
Can you try the latest ID version to see if the problem still occurs there?

**Comment by rubensworks** [comment] 2019-03-08 19:38
@Sir-Will Bump

**Comment by Sir-Will** [comment] 2019-03-08 21:46
I can't update the mod on that server to check at the moment

**Comment by rubensworks** [comment] 2019-03-10 11:04
Closing this as a duplicate of #588. Should you (or anyone else) have any additional information that would help me track down the cause of this problem, be sure to comment in the linked issue.

**Closed as completed by rubensworks** 2019-03-10 11:04 UTC
Labels: duplicate
