### ISSUE TITLE
Crash on joining world after a crash

### ISSUE THREAD

**Issue by AlanCretel** [CyclopsMC/IntegratedDynamics#624] opened 2018-08-28 18:39 UTC
#### Issue type:

- :bug: Bug

____

#### Short description:

A crash that appeared after having a normal crash (Minecraft not responding) and when you join your world

#### Steps to reproduce the problem:

1. Have Minecraft not responding
2. Force Minecraft to crash
3. Restart Game
4. Join the world

#### Expected behaviour:

The screen is fully blue (like in the void but in light blue)
I only have a system that display which liquids I have in my Tinker's Construct Smeltery
____

#### Versions:

----> Crash Report

#### Log file:

Crash report: https://paste.dimdev.org/ebofepewoq.mccrash

**Comment by rubensworks** [comment] 2018-08-28 18:41
Hmm, this should have been fixed in 4c2d45bf614363a62954b7a95c57b8b25aded3c1 already...

I'll need to have another look at this.

**Comment by AlanCretel** [comment] 2018-09-01 19:48
Humm after searchs, I found than this crash occures when placing or when the game charges a pannel with the Practical Logistics 2 mod

**Comment by rubensworks** [comment] 2018-09-02 07:06
That sounds unlikely to be the cause. Does PL2 have any integration with ID somehow? Or are their networks connected?

**Comment by AlanCretel** [comment] 2018-09-02 07:27
I don't seen that PL2 have an integration with ID, I don't have any network connected, does PL2 try to render the display screen with his part renderer ? (PL2 have a display screen too).
In my integrated modpack, I tryed to disable and re-enable mods that I installed before the crash and without PL2 I can join the world (I re-enabled all other mods and nothing change)

**Comment by rubensworks** [comment] 2018-09-03 07:10
It's probably just a coincidence, or PL2 by chance loads some chunks that trigger the issue.

**Comment by AlanCretel** [comment] 2018-09-03 08:34
I don't think, this error occure in all world, when I place or when a display screen is already placed in the world, so if that's a coincidence, I have a lot of chance (If it's a chance lol)

**Closed as completed** 2018-09-09 13:15 UTC
Labels: bug, mc-1.12
