### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by lebanni** [CyclopsMC/IntegratedDynamics#882] opened 2020-06-27 14:29 UTC
forge-1.15.2-31.2.27.jar
IntegratedDynamics-1.15.2-1.1.8.jar
CyclopsCore-1.15.2-1.7.0.jar
CommonCapabilities-1.15.2-2.5.0.jar

Crash during startup.

[crash-2020-06-27_16.17.04-server.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/4840672/crash-2020-06-27_16.17.04-server.txt)
[latest.log](https://github.com/CyclopsMC/IntegratedDynamics/files/4840673/latest.log)

**Comment by rubensworks** [comment] 2020-06-27 15:16
Duplicate of #875

**Closed as completed by rubensworks** 2020-06-27 15:16 UTC
Labels: duplicate
