### ISSUE TITLE
[1.11.2] Weird crafting issue on all other mods

### ISSUE THREAD

**Issue by shortybsd** [CyclopsMC/IntegratedDynamics#122] opened 2017-01-26 04:14 UTC
Minecraft 1.11.2
Forge 2223
IntegratedDynamics-1.11.2-0.6.7

I can no longer craft bonemeal, blaze powder, pretty much anything that uses 1 item to craft something else. How it told on this mod is when I put the item in a Super Crafting Frame, and click the left and right arrows to go through multiple recipes for same output, your mod shows Facade and Variable Card for any single item i put in there. I removed IntegratedDynamics-1.11.2-0.6.7 and poof everything works.

**Comment by rubensworks** [comment] 2017-01-26 07:48
Duplicate of #121, please check other issues before reporting.

**Closed as completed by rubensworks** 2017-01-26 07:48 UTC
Labels: duplicate
