### ISSUE TITLE
Suggestion: Big Multiblock Display Panel

### ISSUE THREAD

**Issue by WestPrime** [CyclopsMC/IntegratedDynamics#1193] opened 2022-07-24 08:43 UTC
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:
Add a multiblock screen like here (https://tmonitoring.com/uploads/files/1523887952_492c7180695c.jpg), that acts like a hi-tech sign which can show some information from variables, because one-block display is too small for big numbers

**Comment by rubensworks** [comment] 2022-07-24 08:44
Thanks for the suggestion!

**Comment by rubensworks** [comment] 2022-07-24 10:19
Duplicate of #273.

**Closed as completed by rubensworks** 2022-07-24 10:19 UTC
Labels: feature-long-term
