### ISSUE TITLE
load variables to the logic programmer 

### ISSUE THREAD

**Issue by HqNw** [CyclopsMC/IntegratedDynamics#1184] opened 2022-06-22 14:57 UTC
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

add the ability to load variables to the logic programmer and or in other way edit them

**Comment by rubensworks** [comment] 2022-06-22 14:57
Thanks for the suggestion!

**Comment by rubensworks** [comment] 2022-06-22 15:04
Duplicate of #357

**Closed as not planned by rubensworks** 2022-06-22 15:04 UTC
Labels: feature-long-term
