### ISSUE TITLE
Chunk loading during unloading

### ISSUE THREAD

**Issue by rakvvv** [CyclopsMC/IntegratedDynamics#1257] opened 2023-04-07 11:50 UTC
#### Issue type:

- :bug: Bug 
whole server crushes
____

#### Short description:

Its a bug with the mod that cause a crash because of erroring cables.
I already reported this bug to the modpack author and they send me here

#### Steps to reproduce the problem:

 
i dont know how to reproduce the bug becuse i cant enter the area in the world that got corrupted

#### Expected behaviour:

my expectation is to recover the corrupted chunks
____

#### Versions:

- This mod: IntegratedDynamisc-1.19.2-1.16.2
- Minecraft: 1.19.2
- Forge: forge-1.19.2-43.2.6

#### Log file:
Log file https://drive.google.com/file/d/1wPaWLqQmPjbO65vUyUh1prPipEioocQE/view?usp=share_link
the crash report :https://pastebin.com/2cEJzNpe

**Comment by rubensworks** [comment] 2023-04-07 12:12
It looks like that crash is being caused by another mod:

```
Caused by: java.lang.RuntimeException: Cable added to position BlockPos{x=1699, y=67, z=2997}, but there was already one there?
	at owmii.powah.block.cable.CableNet.addCable(CableNet.java:24) ~[Powah-4.0.6.jar%23656!/:?] {re:classloading}
	at owmii.powah.block.cable.CableTile.m_6339_(CableTile.java:40) ~[Powah-4.0.6.jar%23656!/:?] {re:classloading}
```

Can you report it to the issue tracker of `Powah`?

**Comment by FyreDraygg** [comment] 2023-06-25 19:34
I have encountered this issue on my server and both Integrated Dynamics and Powah seem to be implicated.

In my case it occurs when trying to stop the server, as it is saving chunks and it completely halts the server process, not even producing a crash report.
After much testing I observed that the issue only occurs when both a network of Logic Cables from Integrated Dynamics and a network of Energy Cables from Powah are present in the same chunk.
In such circumstance, when the server is stopped, the console gets spammed with the error above about cables being added where already present, with the coordinates of one of the Powah Energy Cables.
However, no issue occurs without Integrated Dynamics Logic Cables being there as well.

I commented on an issue on Powah's tracker with this same info:
https://github.com/Technici4n/Powah/issues/90#issuecomment-1606226823

Here's a snippet from my server logs in case it can help shed some light:
https://gist.github.com/FyreDraygg/68afef4db93dd5a2aae7d81f981dc7ad

<blockquote><img src="https://github.githubassets.com/images/modules/gists/gist-og-image.png" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> Gist</div><div><strong><a href="https://gist.github.com/FyreDraygg/68afef4db93dd5a2aae7d81f981dc7ad">Minecraft Server crash during shutdown due to interaction between Integrated Dynamics and Powah</a></strong></div><div>Minecraft Server crash during shutdown due to interaction between Integrated Dynamics and Powah - log_snippet_25-06-2023.txt</div></blockquote>

**Comment by Technici4n** [comment] 2023-06-25 19:39
@rubensworks This is a bug with integrated dynamics that is causing chunks to be loaded again while they are being unloaded. This should be fixed by ID as it can be a performance and correctness concern. I fixed a few similar instances in AE2 recently.

**Comment by rubensworks** [comment] 2023-06-26 06:39
Right, chunk loading during unloading does indeed appear to be a problem.

Note to self: change `invalidatedElements` so that it doesn't rely on current comparator, which relies on loaded chunks.

Nevertheless, the hard-crash does appear to be a problem on Powah's end, which should probably be fixed there as well.

**Closed as completed** 2023-07-08 12:33 UTC
Labels: bug, mc-1.19
