### ISSUE TITLE
Redstone writer not writing properly

### ISSUE THREAD

**Issue by ghost** [CyclopsMC/IntegratedDynamics#483] opened 2018-01-09 06:54 UTC
#### Short description:
When the variable inside a redstone writer changes, the redstone wire (or any redstone detector) doesn't update the signal, I have to either break it or break a block close to it to force it to update 

#### Expected behaviour:
It should update the signal without having to break something.

#### Actual behaviour:
Is not updating the signal

#### Steps to reproduce the problem:

1. Connect a redstone writer with a variable inside that you can change (I tried with an actually additions atomic reconstructor set in deactivation mode and vanilla redstone wire)
2. Make the variable change so the writer outputs or stops outputing the redstone signal
3. Profit

____
#### Versions:
- This mod:  IntegratedDynamics-1.12.2-0.10.0
- CyclopsCore: CyclopsCore-1.12.2-0.11.0
- Minecraft: 1.12.2
- Forge: 1.12.2-forge1.12.2-14.23.1.2555

Honestly I think I may be the only one with this bug since something like this would likely be reported a dozen times already, don't know why it happens, must be a mod interaction or something because I made my own pack.

**Comment by ghost** [comment] 2018-01-09 07:22
So after testing with just ID, IT, Cyclops core, common capabilites and JEI I can confirm it must be some other mod causing it since it works just fine with those 5 mods.

**Comment by rubensworks** [comment] 2018-01-09 10:55
Thanks for reporting, but this is actually a duplicate of #356 (was closed apparently, just reopened it).
Feel free to follow that issue and let me know if there's anything else you can tell about it.

**Closed as completed by rubensworks** 2018-01-09 10:55 UTC
Labels: duplicate
