### ISSUE TITLE
Crash with IC2 .188

### ISSUE THREAD

**Issue by phrostt** [CyclopsMC/IntegratedDynamics#172] opened 2017-04-23 01:31 UTC
IC2 version .188 crashes on startup, here is the crash log.
https://pastebin.com/YtqTJ3hR

**Comment by rubensworks** [comment] 2017-04-23 05:17
Duplicate of CyclopsMC/CommonCapabilities#5, will be fixed in next update.

**Closed as completed by rubensworks** 2017-04-23 05:17 UTC
