### ISSUE TITLE
When Item Importer has Exact Amount = True, it only checks first stack of valid item for given amount

### ISSUE THREAD

**Issue by sbienkow** [CyclopsMC/IntegratedDynamics#580] opened 2018-05-21 14:37 UTC
#### Issue type:

- :bug: Bug

____

#### Short description:

When Item Importer has Exact Amount = True, it only checks first stack of valid item for the amount given with Transfer Rate.

#### Steps to reproduce the problem:

1. Place chest `Chest_Buff`
2. Place chest `Chest_Out` 
3. Place Item Interface on `Chest_Buff`
4. Place Item Exporter on `Chest_Out`
5. Connect the interface and exporter together with cable
6. Place empty variable card in `Import All Items` slot
7. Set `Transfer Rate = 2` and `Exact Amount = true`
8. Place one of any item in the first slot in the `Chest_Buff`
There's 2 paths now:
9a. Place at least 2 of any item in any remaining slot in the `Chest_Buff`
9b. Fill any other slot(s) in `Chest_Buff` with the same item as in step 8, 1 in each slot
    Choose at least one other slot and place item(s) in there
#### Expected behaviour:

Items that there's at least 2 of them in the `Chest_Buff` should be exported to `Chest_Out`
____

#### Versions:

- This mod: 1.12.2-0.11.11
- Minecraft: 1.12.2
- Forge: 14.23.3.2670

**Comment by rubensworks** [comment] 2018-08-16 18:36
FYI, this requires some low-level changes in IT. This will be fixed in the next major release, which will consist of a partial rewrite.

**Comment by rubensworks** [comment] 2018-08-17 16:38
Actually, this seems to be a duplicate of #126.

**Closed as completed by rubensworks** 2018-08-17 16:38 UTC
Labels: bug, duplicate, mc-1.12
