### ISSUE TITLE
MC 1.10 'Stepsound' Crash persists

### ISSUE THREAD

**Issue by KNDickens** [CyclopsMC/IntegratedDynamics#502] opened 2018-01-26 09:02 UTC
I know this issue has been seen and fixed before, however I am still running into it. Multiplayer Server if that makes a difference.

#### Issue type:
- :bug: Bug

____
#### Short description:
Placing the String for a Wet Sponge Step Sound in an Audio Writer crashes the server.
Saw that a fix was found. Installed the most recent 1.10 version of ID (Playing in Skyfactory 3 modpack)

#### Expected behaviour:
Not Crashed Server after install of most recent mod version

#### Actual behaviour:
Crashed Server. Forced a load from backup.

#### Steps to reproduce the problem:

1. Get Block variable card.
2. Get Stepsound (String) variable card of the Block
3. Block in variable store
4. Stepsound in audio writer. (I Get the Achievement right before the crash at least)

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod:  1.10.2-0.7.14
- CyclopsCore:  1.9.4-0.10.9
- Minecraft:   1.10.2
- Forge:  12.18.3.2477

#### Log file:

https://docs.google.com/document/d/1ED9yoaqKYrc_wxr3H1UhIGWIaOrwp7zsEomrDjdGGBE/edit?usp=sharing

**Comment by rubensworks** [comment] 2018-01-26 09:28
Duplicate of #477 and #285.
Only fixed for 1.12, 1.10 is not maintained anymore, sorry.

**Closed as completed by rubensworks** 2018-01-26 09:28 UTC
Labels: duplicate, wontfix, mc-1.10
