### ISSUE TITLE
I hope to add variable card to Integrated Dynamics.

### ISSUE THREAD

**Issue by Gan-N** [CyclopsMC/IntegratedDynamics#812] opened 2020-02-22 06:44 UTC
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

When I add output to technology modules such as Immersive Engineering, the variable card needs to be modified again due to insufficient previous items, but I can only redo or link it with the new addition, hoping to add the content of the variable card to modify

**Comment by rubensworks** [comment] 2020-02-22 10:23
Duplicate of #357

**Closed as completed by rubensworks** 2020-02-22 10:23 UTC
Labels: duplicate
