### ISSUE TITLE
Server Crash while finishing the challenge "Sponge Step Sound".

### ISSUE THREAD

**Issue by DasBrain** [CyclopsMC/IntegratedDynamics#477] opened 2018-01-04 23:01 UTC
#### Issue type:

_Only keep the issue types that are applicable._

- :bug: Bug
____
#### Short description:

Server crashes when trying to get the step sound of a wet sponge.

#### Expected behaviour:

Server does not crash?

#### Actual behaviour:

Server crashes:

#### Steps to reproduce the problem:

1. Get the step sound of a wet sponge block while on a server.

____
#### Versions:

- This mod: 1.12.2-0.9.6
- CyclopsCore: 1.12.2-0.10.23
- Minecraft: 1.12.2
- Forge: 14.23.1.2555

(Direwolf20 1.12 Pack)

#### Log file:

https://pastebin.com/k8KtSDU9

**Comment by DasBrain** [comment] 2018-01-04 23:02
See also https://github.com/CyclopsMC/IntegratedDynamics/issues/285

**Comment by josephcsible** [comment] 2018-01-04 23:15
Duplicate of #392. The latest release contains the fix already.

**Closed as completed by josephcsible** 2018-01-04 23:15 UTC

**Comment by DasBrain** [comment] 2018-01-04 23:16
Sorry, I did search for sponge.
