### ISSUE TITLE
Extreme lag when using lava in mechanical drying basin

### ISSUE THREAD

**Issue by GoldVinyl** [CyclopsMC/IntegratedDynamics#630] opened 2018-10-01 02:05 UTC
#### Issue type:

- :snail: Performance issue

____

#### Short description:

I am running the 2.3.0 version of the **direwolf20** pack. When I use an ender tank to supply lava to a mech. drying basin (and power it), it produces extreme lag as long as the machine is running. The machine only produces lag when I am near it. This problem DOES occur on a new world with no other blocks placed, and it does NOT require an ender tank.

#### Steps to reproduce the problem:

1. Place down a mechanical drying basin.
2. Power the basin, and then feed it lava.
3. You should begin feeling an FPS drop of over 30+ frames.

____

#### Versions:

- This mod: 1.12.2-0.11.17
- Minecraft: 1.12.2
- Forge: 14.23.4.2760
- LWJGL 2: 2.9.4-nightly-20150209
- DW20 Pack: 2.3.0

#### Profiler output:
[dryingbasin.zip](https://github.com/CyclopsMC/IntegratedDynamics/files/2432337/dryingbasin.zip)

NOTE: In case it contributes anything, I am using these java arguments at startup:
-XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

**Comment by rubensworks** [comment] 2018-10-01 06:12
Thanks for reporting, I'll look into it as soon as possible!

**Comment by th4umiel** [comment] 2018-10-06 15:07
Can confirm. I'd say that I start to notice lag the moment I place the mechanical basin, but it seems that the lava worsen the problem.

**Comment by rubensworks** [comment] 2018-10-30 20:00
I don't really see any particular issues in the profiling output, and I don't notice any lag myself when testing.

Does the problem only occur when processing lava? Or also for other recipes?

Does the problem also occur with the Mechanical Squeezer? Or the regular Drying Basin?

**Comment by kainelowen** [comment] 2018-10-30 22:18
Adding that we have this issue on our Stonblocks pack server. The issue happens whenever the mechanical basin is powered, but is dramatically worse when the basin is full and still receiving power. I dro from 60fps to low 20's island partner drops from 60fps to 0. The fps drops are extreme, and happen immediately and then worse in waves of about 20 seconds. Destroying the block immediately fixes it.

**Comment by rubensworks** [comment] 2018-10-31 07:13
@kainelowen It sounds like this may be a block update issue. Could you confirm that you see a lot more chunk updates in the F3 screen when the mechanical basin is present?

**Comment by GoldVinyl** [comment] 2018-11-01 02:24
> 
> 
> @kainelowen It sounds like this may be a block update issue. Could you confirm that you see a lot more chunk updates in the F3 screen when the mechanical basin is present?

I don't believe it is a block update issue because I tested it on an empty world and had the same amount of lag.

**Comment by rubensworks** [comment] 2018-11-01 16:33
I was not able to reproduce the FPS issue myself,
but I discovered some performance issues in TE NBT serialization, which will be fixed in the next CyclopsCore update.

I'm not entirely sure that your issue exactly corresponds to this, so should you still encounter massive lag with the mech drying basin, be sure to let me know here.

**Comment by codewarrior0** [comment] 2018-11-19 08:09
IntegratedDynamics-1.12.2-0.11.17.jar
CyclopsCore-1.12.2-0.11.10.jar

Mechanical Drying Basin causes block updates every tick while processing.

**Comment by codewarrior0** [comment] 2018-11-19 08:19
Same with the Mechanical Squeezer.

**Comment by rubensworks** [comment] 2018-11-19 08:19
Only when it's actively processing I assume?

**Comment by codewarrior0** [comment] 2018-11-19 08:21
Yes, only when processing.

**Comment by Hoff2567** [comment] 2019-01-10 02:46
To add on to this I've noticed it happening with both the mechanical basin and squeezer specifically when power is going in/out of the blocks regardless of if they are actually processing something.

IntegratedDynamics-1.12.2-0.11.18
CyclopsCore-1.12.2-0.11.11
forge-14.23.5.2796

**Comment by Tfarcenim** [comment] 2019-01-31 23:00
![2019-01-30_23-30-19](https://user-images.githubusercontent.com/44327798/52091312-fef52b80-2581-11e9-9fb7-12cbebd80939.gif)
This is still an issue, I drop to 10 FPS when the mechanical drying basin is active

**Comment by XentoniX** [comment] 2019-02-20 19:42
![image](https://user-images.githubusercontent.com/6225228/53119428-c4aef680-354f-11e9-8064-4b56b59a8c80.png)

I can confirm. I get FPS Spike everytime a item is processed. (Mechanical Squeezer).
Since i use 5 in a row when they all work the chunk is unplayable ;D

**Closed as completed** 2019-03-20 19:27 UTC
Labels: performance, mc-1.12
