### ISSUE TITLE
[1.10.2][0.5.1] Redstone Writer does not consistantly output signal

### ISSUE THREAD

**Issue by Aedda** [CyclopsMC/IntegratedDynamics#73] opened 2016-10-03 17:58 UTC
I've been using ID in my test world for a while to turn off rain. It has worked very well for a few days but recently I've been having some problems.

I set up a second Redstone Writer the same way as the first with the proper variables and operator for detecting if the DayTime exceeded 13000. I placed a command block next to the writer to adjust the time.

It however did not work, despite the GUI for the Writer saying "true" for the operator the CB would not trigger. I broke the CB and placed redstone down and it remained unlit. I removed and replaced the operator card and nothing changed "true" disappeared and reappeared and the output remained off.

I then middle-click copied the Writer in creative, broke it, and replaced it. It immediately began emitting a signal. I removed the redstone and put the command block back in place.

This worked for a few cycles and then it got much later than it should with no update 14000 15000 a few times it never triggered. I thought it was just that writer and maybe I botched something. Made sure it was chunk loaded and it was.

Then it began to rain, and no command was triggered to stop it. I visited my ID setup and it said "true" for that Redstone Writer now, yet was not outputting. I copied, broke, replaced it and it immediately began working again.

So it seems at random the Redstone Writers are not updating the block next to them or some such.

**Comment by rubensworks** [comment] 2016-10-03 18:48
I'm not able to reproduce this in the latest dev version.

I did however refactor a lot of stuff related to this, so the problem may have fixed itself already.
I suggest that you try it out again once ID 0.6.0 is released, and let me know how it goes.

I'll leave this issue open for now.

**Comment by rubensworks** [comment] 2016-12-16 10:04
@Aedda Does this problem still occur for you?

**Comment by rubensworks** [comment] 2017-01-20 19:11
Closing this because of unreproducibility in the latest versions.

**Closed as completed by rubensworks** 2017-01-20 19:11 UTC
Labels: unreproducible
