### ISSUE TITLE
Unable to mine with pickaxes with Integrated Dynamics installed

### ISSUE THREAD

**Issue by AllieWade** [CyclopsMC/IntegratedDynamics#1241] opened 2022-12-13 00:09 UTC
#### Issue type:

- :bug: Bug

____

#### Short description:

Unable to mine anything that uses a pickaxe. Pickaxes do not accelerate the mining, and nothing drops.

#### Steps to reproduce the problem:

1. Acquire a pickaxe and mine stone.
2. Receive nothing.

#### Expected behaviour:

Pickaxes work as normal.

____

#### Versions:

Reproduced in a test modpack with the following and nothing else:

- Common Capabiliities: 1.19.2-2.8.3
- Cyclops Core: 1.19.2-1.17.2
- Integrated Dynamics: 1.19.2-1.14.2
- Minecraft: 1.19.2
- Forge: 43.1.65

#### Log file:

Log file shows nothing, but here are the lines from immediately before and after mining.

[18:02:35] [Server thread/INFO]: [Krenshar: Gave 1 [Diamond Pickaxe] to Krenshar]
[18:02:35] [Render thread/INFO]: [System] [CHAT] Gave 1 [Diamond Pickaxe] to Krenshar
[18:02:36] [Server thread/INFO]: Saving and pausing game...

**Comment by rubensworks** [comment] 2022-12-13 00:10
Thanks for reporting!

**Comment by rubensworks** [comment] 2022-12-13 07:18
Duplicate of #1240

**Closed as completed by rubensworks** 2022-12-13 07:18 UTC
Labels: bug, mc-1.19
