### ISSUE TITLE
[1.15.2] crash on start with doggy talents

### ISSUE THREAD

**Issue by Shandoo94** [CyclopsMC/IntegratedDynamics#876] opened 2020-06-25 07:59 UTC
#### Issue type:

- :bug: Bug

____

#### Short description:

Crash on startup with Doggy Talents
May be related to https://github.com/percivalalb/DoggyTalents/issues/194

#### Steps to reproduce the problem:

1. Install Doggy Talents
2. Install Integrated Dynamics
3. Start the game

#### Expected behaviour:

no crash

____

#### Versions:

- This mod: 1.1.6
- Minecraft:  1.15.2 
- Forge: 31.2.8
- Doggy Talents 1.15.2.3

#### Log file:

https://pastebin.com/kpcFyfuP

**Comment by Shandoo94** [comment] 2020-06-25 08:06
https://github.com/MinecraftForge/MinecraftForge/issues/6374

**Comment by rubensworks** [comment] 2020-06-25 11:35
Let me try updating ID to the latest Forge version...

**Comment by rubensworks** [comment] 2020-06-25 14:02
I'm unable to reproduce this problem, even with Doggy Talents installed on the latest Forge version. Could you try without any other mods installed?

**Comment by Shandoo94** [comment] 2020-06-25 15:10
Crash still happens even with only Doggy Talents and Integrated Dynamics installed. Also tested it on Forge 31.2.24. It still crashes

**Comment by rubensworks** [comment] 2020-06-25 15:14
Could you report this at the Doggy Talents issue tracker as well? Because it appears to be a crash in their code.

**Comment by Shandoo94** [comment] 2020-06-25 15:23
It is already reported in https://github.com/percivalalb/DoggyTalents/issues/194
I get the same crash log. The Doggy talents dev says it has to do with forge and links this issue https://github.com/MinecraftForge/MinecraftForge/issues/6374

See https://github.com/percivalalb/DoggyTalents/issues/194#issuecomment-614738900

**Comment by Darkere** [comment] 2020-06-25 20:41
If it is that issue you need to post your latest.log to see what mod is actually causing the issue.

**Comment by Shandoo94** [comment] 2020-06-26 08:05
With the new  update 1.1.7 the crash disapeared but I get https://github.com/CyclopsMC/IntegratedDynamics/issues/880 instead.

**Comment by Shandoo94** [comment] 2020-06-26 08:12
My log for the Issue above is 
https://pastebin.com/9nDm5uXV

Seems that not having installed common capabilities was the issue

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/9nDm5uXV">Integrated Dynamics latest log - Pastebin.com</a></strong></div></blockquote>

**Comment by rubensworks** [comment] 2020-06-26 16:54
Great to hear, closing this one then.

**Closed as completed by rubensworks** 2020-06-26 16:54 UTC
Labels: bug, other mod, mc-1.15
