### ISSUE TITLE
NullpointException when using Integrated Dynamics on Funky Locomotion

### ISSUE THREAD

**Issue by ZeekDaGeek** [CyclopsMC/IntegratedDynamics#476] opened 2018-01-04 22:03 UTC
#### Issue type:

- :bug: Bug

____
#### Short description:
Integrated Dynamics doesn't seem to fail gracefully when it's not able to find an element position. Instead it will crash the server.

#### Expected behaviour:
Be able to move my frame machine without it crashing.

#### Actual behaviour:
It crashed.

#### Steps to reproduce the problem:

1. Put a quickly updating ID Network on a Funky Locomotion platform.
2. Move the platform around a bunch, it won't happen every time, but it will happen.

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: IntegratedDynamics-1.12.2-0.10.0.jar
- CyclopsCore: CyclopsCore-1.12.2-0.11.0.jar
- Minecraft: 1.12.2
- Forge: 14.23.1.2582

#### Log file:

*It's on my server, it's a pain in the butt to get it, here's the most relevant information, plus a screenshot.*
```
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
        at org.cyclops.integrateddynamics.core.network.NetworkElementBase.revalidatePositioned(NetworkElementBase.java:97)
        at org.cyclops.integrateddynamics.core.network.PartNetworkElement.revalidate(PartNetworkElement.java:79)
        at org.cyclops.integrateddynamics.core.network.Network.isValid(Network.java:558)
        at org.cyclops.integrateddynamics.core.network.Network.update(Network.java:394)
        at org.cyclops.integrateddynamics.core.TickHandler.onTick(TickHandler.java:54)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1017_TickHandler_onTick_TickEvent.invoke(.dynamic)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
        at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:264)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:710)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
        at java.lang.Thread.run(Thread.java:748)
```

![The machine](http://zeekdageek.tv/ss/zSHa2.png)

**Comment by josephcsible** [comment] 2018-01-04 23:09
Duplicate of #443

**Closed as completed by josephcsible** 2018-01-04 23:09 UTC
