### ISSUE TITLE
Client crashes when opening Logic Programmer.

### ISSUE THREAD

**Issue by Tylian** [CyclopsMC/IntegratedDynamics#86] opened 2016-11-29 22:06 UTC
Activating the Logic Programmer (block or item), causes the client to crash with this error log: [crash-2016-11-29_17.02.09-client.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/620348/crash-2016-11-29_17.02.09-client.txt)

Happens both in single player and multiplayer. Unsure if this is a mod conflict or not.

**Comment by rubensworks** [comment] 2016-11-30 06:33
Duplicate of #84, has been fixed in CC dev version.

**Closed as completed by rubensworks** 2016-11-30 06:33 UTC
Labels: duplicate
