### ISSUE TITLE
Placing Variable Card in Display Panel causes the game to crash

### ISSUE THREAD

**Issue by ghost** [CyclopsMC/IntegratedDynamics#874] opened 2020-06-14 04:41 UTC
#### Issue type:

- :bug: Bug

____

#### Short description:

I have a variable card made up of a few strings and int's appended onto an empty list. Any time I try to place the final card into a display panel, the game crashes immediately. (All the variables are reading from a TileEntity's NBT).

Note: The display panel dissappears, while the cable glitches out visually.
![2020-06-14_14 37 11](https://user-images.githubusercontent.com/48875125/84584851-a22fa380-ae4c-11ea-8974-75e5c0063c9e.png)

#### Steps to reproduce the problem:

Unknown, card on 1st TileEntity worked, 2nd card (different values, same principle and setup) crashes.

#### Expected behavior:

The variables are concatenated and the result is displayed.

____

#### Versions:

- IntegratedDynamics-1.12.2-1.1.2, IntegratedTunnels-1.12.2-1.6.10
- Minecraft: 1.12.2
- Forge: 1.12.2 - 14.23.5.2847

#### Log file:

https://pastebin.com/7UjkcwC6

**Comment by ghost** [comment] 2020-06-14 04:50
A quick bit of testing shows that as soon as I append 2 values onto a list, it crashes. At the moment it's List(Any) + NBT.String + NBT.Integer which causes the crash. I also had one very weird glitch where all my inventory got swapped around, and then it fixed itself after a second (this happened as soon as I placed in the card). The card returned to my inventory, and on the second attempt it crashed.

**Comment by ghost** [comment] 2020-06-14 05:04
Another edit, I believe this to be an NBT value conversion error. My original (working) cards were using `NBT.Integer` to get an `int` value, but the crashing ones were using `NBT.String`. I fixed the aspect on the cards and I no longer get any errors/crashes.

**Comment by rubensworks** [comment] 2020-06-14 14:54
@EternalClickbait Could you share your full Forge log? I assume some other error occurred before this one.

**Comment by ghost** [comment] 2020-06-17 09:08
I'm afraid I've deleted those logs, but I'll try and reproduce the error again and upload the logs.

**Comment by ghost** [comment] 2020-06-17 10:02
Ok so I got it reproduced. One very weird thing is if I insert the 'breaking' list before the cards it requires, my entire inventory goes weird and the display panel dissappears (but not visually). If I insert the 'breaking' card after it's components, the game crashes.
![2020-06-17_19 44 12](https://user-images.githubusercontent.com/48875125/84882960-50e51580-b0d3-11ea-8e08-9a39f61f136f.png)
![2020-06-17_19 44 29](https://user-images.githubusercontent.com/48875125/84882967-53e00600-b0d3-11ea-8824-1acb9b623695.png)

Crash file + Logs + Recording are too large for GitHub, here's a google drive link to the zip https://drive.google.com/file/d/1_eYgmU2kyb5MVeetK6yCa8wwsE5jQ3vf/view?usp=sharing 

<blockquote><img src="https://ssl.gstatic.com/docs/doclist/images/icon_14_generic_favicon.ico" width="48" align="right"><div>Google Docs</div><div><strong><a href="https://drive.google.com/file/d/1_eYgmU2kyb5MVeetK6yCa8wwsE5jQ3vf/view?usp=sharing&usp=embed_facebook">Integrated Dynamics NBT Cast Crash.zip</a></strong></div></blockquote>

**Comment by rubensworks** [comment] 2020-06-17 10:03
Thanks!

**Comment by rubensworks** [comment] 2020-07-08 18:02
Ok, so the problem seems to be caused by erroring tile entities, which are being reset behind the scenes, and cause a crash later on.

I was unfortunately not able to reproduce this problem myself, but with your logs I was able to pinpoint the possible cause, and add some debug information to the logs.
@EternalClickbait Could you try out the latest dev build (see README of this repo), and share the full logs with me again after the crash?

**Comment by rubensworks** [comment] 2020-07-08 18:43
_May_ be related to #866 if _map_ operations were used.

**Comment by ghost** [comment] 2020-07-22 09:16
I've tried to reproduce it, but for some reason it is no longer crashing. When trying to get an NBT value using the wrong type, it simply displays the default value, so I assume you fixed whatever it was. BTW I used v1.12.2-1.1.7

Edit: Heres the log 
[latest.log](https://github.com/CyclopsMC/IntegratedDynamics/files/4959074/latest.log)

**Comment by rubensworks** [comment] 2020-07-22 09:19
@EternalClickbait Thanks for checking, seems like it was fixed in #866 then.

**Closed as completed by rubensworks** 2020-07-22 09:19 UTC
Labels: bug
