### ISSUE TITLE
Rendering bugs in chunk with a complex InDy system

### ISSUE THREAD

**Issue by met4000** [CyclopsMC/IntegratedDynamics#1300] opened 2023-08-19 08:43 UTC
#### Issue type:

- :bug: Bug 

____

#### Short description:

Blocks appear invisible when placed, or an entire chunk is not rendered correctly. This can happen immediately after loading in, or start after some time within the world.

https://github.com/CyclopsMC/IntegratedDynamics/assets/15624876/7d829617-eb3b-4a22-8e42-9f6aa667a085

#### Steps to reproduce the problem:

World:
[FillCrash.zip](https://github.com/CyclopsMC/IntegratedDynamics/files/12385390/FillCrash.zip)

1. load the world in the zip
2. wait (has varied for me from being as soon as I load into the world, to a few seconds or mins, to something like 15 mins)

It is more common for things to be invisible (e.g. as in the second half of the video) rather than the chunk to not render (as in the first  half of the video). The invisibility has also occurred after some time on other saves with multiple but less complex networks/systems than this one.

#### Expected behaviour:

Chunk is rendered correctly, and blocks are not invisible when placed.

____

#### Versions:

- Minecraft: 1.20.1
- Forge: 47.1.0

![261781221-5cd6111a-adf9-4e03-8231-b094e9828d94](https://github.com/CyclopsMC/IntegratedDynamics/assets/15624876/66abc967-25a5-4584-aa37-1e28f2dd1db7)

#### Log file:
N/A

**Comment by rubensworks** [comment] 2023-08-19 08:43
Thanks for reporting!

**Comment by rubensworks** [comment] 2023-08-26 16:06
Just tested with your world, and I can confirm the problem.

However, nothing seems to be going wrong in ID's rendering logic AFAICS (no exceptions being thrown or so).
Furthermore, since this doesn't seem to occur in older MC versions, this may be a MC-version-specific problem (perhaps similar to https://bugs.mojang.com/browse/MC-245010 ).

So I'll have to close this one as can't-fix.

<blockquote><img src="/s/kxclkf/990001/16nkl1v/_/jira-favicon-hires.png" width="48" align="right"><div><strong><a href="https://bugs.mojang.com/browse/MC-245010">Loading...</a></strong></div></blockquote>

**Closed as not planned by rubensworks** 2023-08-26 16:06 UTC
Labels: bug, mc-1.20
