### ISSUE TITLE
Crash on server launch

### ISSUE THREAD

**Issue by Sunekaer** [CyclopsMC/IntegratedDynamics#1095] opened 2021-09-29 19:26 UTC
#### Issue type:

- :bug: Bug

____

#### Short description:

Crash on server launch

#### Steps to reproduce the problem:

start server

#### Expected behaviour:

to not crash

____

#### Versions:

- This mod: IntegratedDynamics-1.16.5-1.10.0.jar      
- Minecraft: 1.16.5
- Forge: 36.2.2

#### Log file:

https://paste.sunekaer.com/bizohacuyo.rb

**Comment by rubensworks** [comment] 2021-09-29 19:26
Thanks for reporting!

**Comment by rubensworks** [comment] 2021-09-30 04:23
Duplicate of #1093. New release is pending on CurseForge.

**Closed as completed by rubensworks** 2021-09-30 04:23 UTC
Labels: bug, mc-1.16
